name: kpostal
description: Kpostal package can search for Korean postal addresses using Kakao postcode service. This package is inspired by Kopo package that is discontinued.
version: 0.2.0
homepage: https://github.com/tykann/kpostal

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.10
  flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/kakao_postcode_localhost.html
